files:
  - source: /StrongBox/CustomCells/
    translation: /StrongBox/%two_letters_code%/CustomCells/%original_file_name%
  - source: /StrongBox/*.strings
    translation: /StrongBox/%two_letters_code%/%original_file_name%
  - source: /StrongBox Auto Fill/*.strings
    translation: /StrongBox Auto Fill/%two_letters_code%/%original_file_name%
  - source: /MacBox/*.strings
    translation: /MacBox/%two_letters_code%/%original_file_name%
